import type { Invoice, InvoiceStatus } from './types'
import { formatIstDateTime } from './dateUtils'

const STATUS_LABEL: Record<InvoiceStatus, string> = {
  submitted: 'Submitted',
  im_review: 'IM review',
  im_approved: 'IM approved',
  audit_cleared: 'Audit Cleared',
  partially_paid: 'Partially Paid',
  audit_rejected: 'Audit Rejected',
  payer_rejected_audit: 'Payment rejected (audit)',
  payer_rejected_im: 'Payment rejected (IM)',
  released: 'Payment released',
  rejected: 'Rejected',
}

export function hasUploadedInvoicePdf(invoice: Invoice): boolean {
  return Boolean(invoice.invoice_file_url?.trim())
}

/** Client-side PDF for auto-generated (non-uploaded) invoices */
export async function downloadAutoGeneratedInvoicePdf(invoice: Invoice): Promise<void> {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF()
  const margin = 14
  const pageW = doc.internal.pageSize.getWidth()
  const maxW = pageW - margin * 2
  let y = 20

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('Invoice', margin, y)
  y += 10

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(110)
  doc.text('Auto-generated summary · OnO', margin, y)
  doc.setTextColor(0)
  y += 12

  const gstAmt = invoice.gst ? invoice.amount * 0.18 : 0
  const total = invoice.amount + gstAmt

  const rows: [string, string][] = [
    ['Invoice ID', invoice.id],
    ['Status', STATUS_LABEL[invoice.status]],
    ['Campaign', invoice.campaign],
    ['Creator', invoice.creator_name],
    ['Assigned IM', invoice.assigned_im],
    ['Base amount', `₹${invoice.amount.toLocaleString('en-IN')}`],
    ['GST (18%)', invoice.gst ? `₹${gstAmt.toLocaleString('en-IN', { maximumFractionDigits: 2 })}` : 'Not applicable'],
    ['Total', `₹${total.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`],
    ['Submitted', formatIstDateTime(invoice.created_at)],
  ]

  if (invoice.pan) rows.push(['PAN', invoice.pan])
  if (invoice.gst_number) rows.push(['GST number', invoice.gst_number])
  if (invoice.account_holder_name) rows.push(['Account holder', invoice.account_holder_name])
  if (invoice.account_no) rows.push(['Account number', invoice.account_no])
  if (invoice.ifsc) rows.push(['IFSC', invoice.ifsc])
  if (invoice.status === 'rejected' && invoice.rejection_note) {
    rows.push(['Rejection note', invoice.rejection_note])
  }

  doc.setFontSize(10)
  for (const [label, value] of rows) {
    doc.setFont('helvetica', 'bold')
    doc.text(`${label}:`, margin, y)
    doc.setFont('helvetica', 'normal')
    const wrapped = doc.splitTextToSize(value, maxW - 42)
    doc.text(wrapped, margin + 40, y)
    y += Math.max(6, wrapped.length * 5) + 3
    if (y > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage()
      y = 20
    }
  }

  const safeName = invoice.id.replace(/[^\w.-]+/g, '_')
  doc.save(`${safeName}.pdf`)
}
