import toast from 'react-hot-toast'
import { getInvoiceFileSignedUrl, resolveMediaUrl } from './api'
import { downloadAutoGeneratedInvoicePdf } from './invoicePdf'
import type { Invoice } from './types'

export function hasUploadedPdfFile(invoice: Invoice): boolean {
  const pdfUrl = invoice.pdf_url
  if (typeof pdfUrl === 'string' && pdfUrl.trim().length > 0) return true
  const u = invoice.invoice_file_url
  return typeof u === 'string' && u.trim().length > 0
}

export function hasBackendPdf(invoice: Invoice): boolean {
  const pdfUrl = invoice.pdf_url
  return typeof pdfUrl === 'string' && pdfUrl.trim().length > 0
}

export async function handleInvoiceView(
  invoice: Invoice,
  onViewTimeline: (inv: Invoice) => void
): Promise<void> {
  if (hasBackendPdf(invoice) || hasUploadedPdfFile(invoice)) {
    try {
      if (hasBackendPdf(invoice)) {
        const u = resolveMediaUrl(invoice.pdf_url!.trim())
        window.open(u, '_blank', 'noopener,noreferrer')
      } else {
        const signedUrl = await getInvoiceFileSignedUrl(invoice.id, invoice.invoice_file_url)
        window.open(signedUrl, '_blank', 'noopener,noreferrer')
      }
    } catch (err) {
      console.error('[invoice View] PDF open failed:', err)
      toast.error('Could not open PDF')
    }
  } else {
    onViewTimeline(invoice)
  }
}

export async function handleInvoiceDownload(invoice: Invoice): Promise<void> {
  if (hasBackendPdf(invoice) || hasUploadedPdfFile(invoice)) {
    try {
      const url = hasBackendPdf(invoice)
        ? resolveMediaUrl(invoice.pdf_url!.trim())
        : await getInvoiceFileSignedUrl(invoice.id, invoice.invoice_file_url)
      const res = await fetch(url)
      if (!res.ok) {
        throw new Error(`HTTP ${res.status}`)
      }
      const blob = await res.blob()
      const objectUrl = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = objectUrl
      a.download = 'Invoice.pdf'
      document.body.appendChild(a)
      a.click()
      a.remove()
      window.URL.revokeObjectURL(objectUrl)
    } catch (err) {
      console.error('[invoice Download] PDF download failed (network/CORS/etc.):', err)
      toast.error('Could not download PDF')
    }
  } else {
    try {
      await downloadAutoGeneratedInvoicePdf(invoice)
    } catch (err) {
      console.error('[invoice Download] jsPDF generation failed:', err)
      toast.error('Could not generate PDF')
    }
  }
}
