import { useNavigate } from 'react-router-dom'
import toast from 'react-hot-toast'
import { fetchAuthenticatedBlob } from '../../lib/api'
import {
  downloadAutoGeneratedInvoicePdf,
  hasUploadedInvoicePdf,
} from '../../lib/invoicePdf'
import type { Invoice } from '../../lib/types'
import { cn } from '../../lib/utils'

const linkStyles =
  'text-xs font-medium text-accent-2 underline-offset-2 transition-colors hover:text-accent hover:underline'

interface InvoicePdfActionsProps {
  invoice: Invoice
  /** Route to the timeline / detail view (auto-generated invoices) */
  detailPath: string
  /** Optional `navigate` state (e.g. IM approved list back navigation) */
  detailState?: Record<string, unknown>
  className?: string
  linkClassName?: string
}

export function InvoicePdfActions({
  invoice,
  detailPath,
  detailState,
  className,
  linkClassName,
}: InvoicePdfActionsProps) {
  const navigate = useNavigate()

  async function handleView(e: React.MouseEvent) {
    e.stopPropagation()
    if (hasUploadedInvoicePdf(invoice)) {
      try {
        const blob = await fetchAuthenticatedBlob(invoice.invoice_file_url!)
        const url = URL.createObjectURL(blob)
        window.open(url, '_blank', 'noopener,noreferrer')
        window.setTimeout(() => URL.revokeObjectURL(url), 120_000)
      } catch {
        toast.error('Could not open PDF')
      }
    } else {
      navigate(detailPath, detailState ? { state: detailState } : undefined)
    }
  }

  async function handleDownload(e: React.MouseEvent) {
    e.stopPropagation()
    if (hasUploadedInvoicePdf(invoice)) {
      try {
        const blob = await fetchAuthenticatedBlob(invoice.invoice_file_url!)
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `${invoice.id.replace(/[^\w.-]+/g, '_')}.pdf`
        a.rel = 'noopener'
        a.click()
        URL.revokeObjectURL(url)
      } catch {
        toast.error('Could not download PDF')
      }
    } else {
      try {
        await downloadAutoGeneratedInvoicePdf(invoice)
      } catch {
        toast.error('Could not generate PDF')
      }
    }
  }

  return (
    <div
      className={cn('flex flex-wrap items-center gap-x-2 gap-y-1', className)}
      onClick={(e) => e.stopPropagation()}
    >
      <button
        type="button"
        onClick={handleView}
        className={linkClassName ?? linkStyles}
      >
        View
      </button>
      <span className="select-none text-[10px] text-text-3" aria-hidden>
        ·
      </span>
      <button
        type="button"
        onClick={handleDownload}
        className={linkClassName ?? linkStyles}
      >
        Download
      </button>
    </div>
  )
}
