import toast from 'react-hot-toast'
import { fetchAuthenticatedBlob } from '../../lib/api'
import { downloadAutoGeneratedInvoicePdf } from '../../lib/invoicePdf'
import type { Invoice } from '../../lib/types'
import { cn } from '../../lib/utils'

const linkStyles =
  'text-xs font-medium text-accent-2 underline-offset-2 transition-colors hover:text-accent hover:underline'

function hasUploadedPdfFile(invoice: Invoice): boolean {
  const u = invoice.invoice_file_url
  return typeof u === 'string' && u.trim().length > 0
}

interface InvoicePdfActionsProps {
  invoice: Invoice
  /** Auto-generated invoices: open timeline/detail UI (e.g. setSelectedInvoice) — do not open a PDF */
  onViewTimeline: (invoice: Invoice) => void
  className?: string
  linkClassName?: string
}

export function InvoicePdfActions({
  invoice,
  onViewTimeline,
  className,
  linkClassName,
}: InvoicePdfActionsProps) {
  async function handleView(e: React.MouseEvent) {
    e.stopPropagation()
    console.log('Action clicked for:', invoice)

    if (hasUploadedPdfFile(invoice)) {
      try {
        const blob = await fetchAuthenticatedBlob(invoice.invoice_file_url!.trim())
        const url = URL.createObjectURL(blob)
        window.open(url, '_blank', 'noopener,noreferrer')
        window.setTimeout(() => URL.revokeObjectURL(url), 120_000)
      } catch {
        toast.error('Could not open PDF')
      }
    } else {
      onViewTimeline(invoice)
    }
  }

  async function handleDownload(e: React.MouseEvent) {
    e.stopPropagation()
    console.log('Action clicked for:', invoice)

    if (hasUploadedPdfFile(invoice)) {
      try {
        const blob = await fetchAuthenticatedBlob(invoice.invoice_file_url!.trim())
        const objectUrl = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = objectUrl
        a.download = `${invoice.id.replace(/[^\w.-]+/g, '_')}.pdf`
        a.rel = 'noopener'
        a.style.display = 'none'
        a.style.position = 'absolute'
        a.style.left = '-9999px'
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        window.setTimeout(() => URL.revokeObjectURL(objectUrl), 2500)
      } catch {
        toast.error('Could not download PDF')
      }
    } else {
      try {
        await downloadAutoGeneratedInvoicePdf(invoice)
      } catch {
        toast.error('Could not generate PDF')
      }
    }
  }

  return (
    <div
      className={cn('flex flex-wrap items-center gap-x-2 gap-y-1', className)}
      onClick={(e) => e.stopPropagation()}
    >
      <button type="button" onClick={handleView} className={linkClassName ?? linkStyles}>
        View
      </button>
      <span className="select-none text-[10px] text-text-3" aria-hidden>
        ·
      </span>
      <button type="button" onClick={handleDownload} className={linkClassName ?? linkStyles}>
        Download
      </button>
    </div>
  )
}
