import toast from 'react-hot-toast'
import { getInvoiceFileSignedUrl } from '../../lib/api'
import { downloadAutoGeneratedInvoicePdf } from '../../lib/invoicePdf'
import type { Invoice } from '../../lib/types'
import { cn } from '../../lib/utils'

const linkStyles =
  'text-xs font-medium text-accent-2 underline-offset-2 transition-colors hover:text-accent hover:underline'

/** Truthy non-empty invoice_file_url means an uploaded PDF exists */
function hasUploadedPdfFile(invoice: Invoice): boolean {
  const u = invoice.invoice_file_url
  return typeof u === 'string' && u.trim().length > 0
}

interface InvoicePdfActionsProps {
  invoice: Invoice
  /** Auto-generated: open timeline/detail (e.g. setSelectedInvoice / setTimelineInvoice) */
  onViewTimeline: (invoice: Invoice) => void
  className?: string
  linkClassName?: string
}

export function InvoicePdfActions({
  invoice,
  onViewTimeline,
  className,
  linkClassName,
}: InvoicePdfActionsProps) {
  async function handleView(e: React.MouseEvent) {
    e.stopPropagation()

    if (hasUploadedPdfFile(invoice)) {
      try {
        const signedUrl = await getInvoiceFileSignedUrl(invoice.id, invoice.invoice_file_url)
        window.open(signedUrl, '_blank', 'noopener,noreferrer')
      } catch (err) {
        console.error('[invoice View] PDF open failed:', err)
        toast.error('Could not open PDF')
      }
    } else {
      onViewTimeline(invoice)
    }
  }

  async function handleDownload(e: React.MouseEvent) {
    e.stopPropagation()

    if (hasUploadedPdfFile(invoice)) {
      try {
        const signedUrl = await getInvoiceFileSignedUrl(invoice.id, invoice.invoice_file_url)
        const res = await fetch(signedUrl)
        if (!res.ok) {
          throw new Error(`HTTP ${res.status}`)
        }
        const blob = await res.blob()
        const objectUrl = window.URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = objectUrl
        a.download = 'Invoice.pdf'
        document.body.appendChild(a)
        a.click()
        a.remove()
        window.URL.revokeObjectURL(objectUrl)
      } catch (err) {
        console.error('[invoice Download] PDF download failed (network/CORS/etc.):', err)
        toast.error('Could not download PDF')
      }
    } else {
      try {
        await downloadAutoGeneratedInvoicePdf(invoice)
      } catch (err) {
        console.error('[invoice Download] jsPDF generation failed:', err)
        toast.error('Could not generate PDF')
      }
    }
  }

  return (
    <div
      className={cn('flex flex-wrap items-center gap-x-2 gap-y-1', className)}
      onClick={(e) => e.stopPropagation()}
    >
      <button type="button" onClick={handleView} className={linkClassName ?? linkStyles}>
        View
      </button>
      <span className="select-none text-[10px] text-text-3" aria-hidden>
        ·
      </span>
      <button type="button" onClick={handleDownload} className={linkClassName ?? linkStyles}>
        Download
      </button>
    </div>
  )
}
